### ISSUE TITLE
perf(db): improve `bookmarkEntries` read

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v3#333]
I'm doubting the usefulness of `/bookmarks` page itself, so maybe we should't go over-engineer anything yet.

## todo

- [x] `(userId, createdAt)` index https://github.com/hi-ogawa/ytsub-v3/pull/335
- [ ] infinite loading with no count
- [x] ~lazy load `captionEntries/videos` on client~ (this is not necessary as long as we do deferred join for infinite load query above)

## planetscale insight 

![image](https://user-images.githubusercontent.com/4232207/235403797-9822b843-d780-4e30-8d1f-0370e9ad1b6a.png)
