### ISSUE TITLE
chore: cleanup planetscale db branches?

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v3#342]
For some legacy reason, current branches look like this:

![image](https://user-images.githubusercontent.com/4232207/235550383-415511dd-472c-4f0b-ab51-458d4ed88262.png)

It looks like now we can disable "safe migration" (https://planetscale.com/blog/update-to-our-workflow-safe-migrations), which means I can finally remove `main--us-east-1` and then recreate a new development branch for staging?

**Comment by hi-ogawa** [comment]
## todo

- [ ] disable "safe migration" on legacy production branch `main--us-east-1`
- [ ] promote `main` to new production branch
- [ ] delete `main--us-east-1`
- [ ] create new development branch `main-staging`
- [ ] ...

**Comment by hi-ogawa** [comment]
Well, we still cannot delete `main--us-east-1` since that's the base branch of `main`...
Probably it'll re-creating a whole `main` database after deleting everything, which is not probably what we want to do right now.

**Comment by hi-ogawa** [comment]
## todo (production)

- [ ] dump `ytsub_production/main`

```sh
pscale org switch hiro18181-ytsub
pscale database dump ytsub_production main
```

- [ ] delete all branches on planetscale
- [ ] create `ytsub_production/main`
- [ ] restore dump

```sh
pscale database restore-dump
```

- [ ] update credentials
  - `.env.production` (local)
  - vercel deployement
