### ISSUE TITLE
feat: revamp user credentials

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v3#393]
## references

let's review with some common standard e.g.

- https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html
- https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

## todo

- [x] username case insensitive
  - actually it's already the case because of `COLLATE=utf8mb4_0900_ai_ci`
  - https://github.com/hi-ogawa/ytsub-v3/pull/395
- [x] optional email to reset password https://github.com/hi-ogawa/ytsub-v3/pull/401
- [x] reduct `users.passwordHash` from client response https://github.com/hi-ogawa/ytsub-v3/pull/406
- [ ] password limit instead of pre hash sha256
- [ ] replace bcrypt with argon2
- [ ] ~explicitly expire-able session?~ (later)
