### ISSUE TITLE
chore: netlify edge experiment

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub-v3#54]
- https://docs.netlify.com/netlify-labs/experimental-features/edge-functions
- https://github.com/remix-run/remix/tree/experimental-netlify-edge
  - https://github.com/remix-run/remix/pull/2866
  - https://github.com/netlify/remix-edge-template
- https://github.com/netlify/cli
  - https://github.com/netlify/cli/pull/4550
  - https://github.com/netlify/cli/tree/main/src/lib/edge-functions
  - https://github.com/netlify/edge-bundler
  - https://github.com/netlify/build

## todo

- [ ] reverse engineering netlify-cli
- [ ] understand runtime
- [ ] understand build
  - [x] use cli
  - [x] use "internal" manifest
  - [ ] ~use edge-bundler~
  - [ ] use own script
- [ ] remix integration
  - use template (and remix experimental branch)
  - use own patch
  - server config
    - `ServerBuildTarget`, `ServerModuleFormat`, `ServerPlatform`
  - dependencies resolution
    - need to emit "import map"? (or does "edge bundler" do it?)
    - switch "implementations" from "remix-node" to "remix-deno"
- [ ] routing priority (cf. `context.next` https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/api/#netlify-specific-context-object)
  - static assets
  - `routes` in `minifest.json`
  - `redirect` in `netlify.toml`
  - delegate by returning `undefined`
- [ ] cpu limit
- [ ] setup deno development
  - deno compatible tsc
  - editor

**Comment by hi-ogawa** [comment]
## reverse engineering

based on hello world app https://docs.netlify.com/netlify-labs/experimental-features/edge-functions/get-started/

### `netlify dev`

```sh
$ netlify --version
netlify-cli/10.1.0 linux-x64 node-v14.19.1
```

```sh
$ pgrep -a -f netlify
1369473 netlify dev
1369475 node /home/hiroshi/.volta/tools/image/packages/netlify-cli/bin/netlify dev
1369720 /home/hiroshi/.config/netlify/deno-cli/deno run --allow-all --unstable --import-map=data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS1ib290c3RyYXAubmV0bGlmeS5hcHAvdjEvaW5kZXgudHMifX0= --quiet /tmp/tmp-1369475-VvX8lfTGcyV5/dev.js 42045
```

- `.netlify/edge-functions-import-map.json`

```json
{"imports":{"netlify:edge":"https://edge-bootstrap.netlify.app/v1/index.ts"}}
```

```sh
$ curl https://edge-bootstrap.netlify.app/v1/index.ts
export type { Context } from "../bootstrap/context.ts";
export type { EdgeFunction } from "../bootstrap/edge_function.ts";
```

- ` /tmp/tmp-1369475-VvX8lfTGcyV5/dev.js`

```js
import { boot } from "https://625d32be1b90870009edfc99--edge-bootstrap.netlify.app/bootstrap/index-combined.ts";

const functions = {};


  try {
    const { default: func } = await import("file:///home/hiroshi/code/personal/ytsub-v3/netlify-edge/netlify/edge-functions/hello.js");

    if (typeof func === "function") {
      functions["hello"] = func;
    } else {
      console.log("\u001b[91m◈\u001b[39m \u001b[31mFailed\u001b[39m to load Edge Function \u001b[33mhello\u001b[39m. The file does not seem to have a function as the default export.");
    }
  } catch (error) {
    console.log("\u001b[91m◈\u001b[39m \u001b[31mFailed\u001b[39m to run Edge Function \u001b[33mhello\u001b[39m:");
    console.error(error);
  }
  

boot(functions);
```

**Comment by hi-ogawa** [comment]
### `netlify build`

```
$ netlify build
...
────────────────────────────────────────────────────────────────
  1. Edge Functions bundling                                    
────────────────────────────────────────────────────────────────

Packaging Edge Functions from netlify/edge-functions directory:
 - hello

(Edge Functions bundling completed in 1.9s)

────────────────────────────────────────────────────────────────
  Netlify Build Complete                                        
────────────────────────────────────────────────────────────────

(Netlify Build completed in 2s)

```

- `.netlify/edge-functions-dist/manifest.json`

```json
{
  "bundles": [
    {
      "asset": "839869060036ab59a60b1d7e0eac1648ee117f19baf968acd3d3f6e35fb5f280.js",
      "format": "js"
    }
  ],
  "routes": [
    {
      "function": "hello",
      "pattern": "^/test$"
    }
  ],
  "bundler_version": "0.12.0"
}
```

- `.netlify/edge-functions-dist/839869060036ab59a60b1d7e0eac1648ee117f19baf968acd3d3f6e35fb5f280.js`

```js
...
function __default() {
    return new Response("Hey");
}
const functions = {
    "hello": __default
};
serve1(functions);
```
